# Generated by Django 5.0.1 on 2024-02-12 17:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
                ('topic', models.CharField(choices=[('CSS', 'CSS'), ('HTML', 'HTML'), ('JAVASCRIPT', 'JavaScript'), ('PYTHON', 'Python'), ('RUBY', 'Ruby'), ('PROGRAMMING', 'Programming')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
