# Generated by Django 5.0.1 on 2024-02-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='Default title', max_length=30),
        ),
    ]
