# Generated by Django 5.0.1 on 2024-02-15 19:42

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/profile_pics/default.jpeg', upload_to=user_profile.models.getcurrentusername),
        ),
    ]
